# .readthedocs.yaml

version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

# Tell Read the Docs to install your project's dependencies
python:
   install:
   - method: pip
     path: .

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/conf.py
